#!/bin/sh
# xset_status
#
# Set the name of the root window, to show the basic system status.
# This script is intended to be used with dwm.
#
# Usage: xset_status
#

print_network_device() {
    # print the connected device type.
    # show only the default top, even when multiple devices are connected.
    dev=$(ip route | grep default | sed -e 's/^.*dev //' -e 's/ .*//' | head -n 1)
    # when multiple devices are connected, the device names are separated with ORS.
    # dev=$(nmcli device | awk 'BEGIN { ORS = "" } {if ($3 == "connected") { print $2" " }}')
    test "${dev}" && echo "[${dev}]"
}

print_fcitx_status() {
    # print "fcitx" if fcitx is installed and active.
    test "$(command -v fcitx-remote)" && test "$(fcitx-remote)" -eq 2 && echo "[fcitx]"
}

print_battery_status() {
    # print remaining battery in percentage
    battery_info_files="$(ls /sys/class/power_supply/*BAT*/capacity)"
    test "${battery_info_files}" && awk '{ sum += $1 } END { print "["sum"%]" }' "${battery_info_files}"
}

print_load_avg() {
    # print the load average during the last minite
    sed -e 's/ .*//' /proc/loadavg
}

print_datetime() {
    # date
    date "+%a%d%b/%H:%M"
}

while true
do
    xsetroot -name " $(print_load_avg) $(print_fcitx_status)$(print_network_device)$(print_battery_status) $(print_datetime)"
    sleep 0.5
done
