#!/bin/bash
# Open a browser

HOME_PAGE=localhost:33876

if command -v firefox > /dev/null; then
    mkdir -p ${HOME}/.cache/mozilla
    firefox ${HOME_PAGE}
elif command -v chromium > /dev/null; then
    mkdir -p ${HOME}/.cache/chromium
    chromium ${HOME_PAGE}
fi

