#!/bin/bash

test "$(command -v map_capslock_to_ctrl)" && map_capslock_to_ctrl

# Allow Japanese input with fcitx.
# https://wiki.archlinux.org/index.php/Fcitx#Emacs

# If LC_CTYPE is English, you may not be able to use input method in emacs due
# to an old emacs bug. You can set LC_CTYPE to something else such as
# zh_CN.UTF-8 before emacs starts to get rid of this problem.

# Note that the corresponding locale should be uncommented in /etc/locale.gen
# and locale-gen should be run as su.

if locale -a | grep -q -e '^ja_JP.utf8'; then
    LC_CTYPE=ja_JP.UTF-8 /usr/bin/emacs "$@" &
else
    /usr/bin/emacs "$@" &
fi

