#!/bin/bash

containers=$(docker ps -a -q)
if [[ ${containers} != "" ]]; then
    docker stop ${containers}
fi

containers=$(docker ps -a -q)
if [[ ${containers} != "" ]]; then
    docker rm ${containers}
fi
