#!/bin/sh

cmd=${*}
# remove forward slash from the first argument
dir_prefix=${1##/*/}
sandboxes_dir=${HOME}/tmp/sandboxes

sandbox_name=''

chooseName () {

    candidate=${dir_prefix}${1}

    if [ ! -d "${sandboxes_dir}/${candidate}" ]; then
        sandbox_name=${candidate}
        return 0
    else
        chooseName $(( "${1}" + 1 ))
    fi

}

chooseName 0
sandbox_dir=${sandboxes_dir}/${sandbox_name}
mkdir -p "${sandbox_dir}"

echo "Running ${dir_prefix}"
echo "Sandbox name is ${sandbox_name}"

# --caps.drop=all
#    Drop all capabilities for the processes running in the sandbox.  This
#    option is recommended for running GUI programs or any other program that
#    doesn't require root privileges.

# --disable-mnt
#    Disable /mnt, /media, /run/mount and /run/media access.

# --noroot
#    Install a user namespace with a single user - the current user.  root user
#    does not exist in the new namespace.

# --private-tmp
#    Mount an empty temporary filesystem on top of /tmp directory whitelisting
#    X11 and PulseAudio sockets.

# --quiet
#    Turn off Firejail's output.

firejail --caps.drop=all --disable-mnt --noroot --private-tmp --quiet \
    --name="${sandbox_name}" --private="${sandbox_dir}" --whitelist=~/.config/fcitx \
    --seccomp --protocol=unix,inet,inet6,netlink ${cmd}

trap 'rm -rf "${sandbox_dir}"' EXIT
