#!/bin/sh
# Open terminal emulator.

test "$(command -v map_capslock_to_ctrl)" && map_capslock_to_ctrl

if command -v alacritty > /dev/null; then
    alacritty
elif command -v xterm > /dev/null; then
    xrdb -merge "${HOME}/.Xresources"
    xterm
elif command -v st > /dev/null; then
    # suckless simple terminal
    st 2> /dev/null &
elif command -v xfce4-terminal > /dev/null; then
    xfce4-terminal
else
    # URXVT
    xrdb -merge "${HOME}/.Xresources"
    /usr/bin/urxvt 2> /dev/null &
fi

