# .zshrc
# See also /etc/zshrc

# Environment variables
export LESS="-r"  # color support
export GREP_COLOR='1;33'  # color grep output in yellow

# ALIASES
# =======
alias ls='/bin/ls --color=auto'
alias mkdir='mkdir -v'
alias mv='mv -iv'
alias cp='cp -i -p'
alias rm='rm -iv'
alias grep='grep --color=always'

# HISTORY
# =======
HISTSIZE=10000
SAVEHIST=10000
setopt SHARE_HISTORY  # share history between sessions

# KEYBINDINGS
# ===========
# Make sure the terminal is in application mode, when zle is active. Only then
# are the values from $terminfo valid.
if (( ${+terminfo[smkx]} && ${+terminfo[rmkx]} )); then
    autoload -Uz add-zle-hook-widget
    function zle_application_mode_start { echoti smkx }
    function zle_application_mode_stop { echoti rmkx }
    add-zle-hook-widget -Uz zle-line-init zle_application_mode_start
    add-zle-hook-widget -Uz zle-line-finish zle_application_mode_stop
fi

# Show only the past commands matching the current line up to the current cursor
# position when Up or Down keys are pressed.
autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
[[ -n ${key[Up]} ]] && bindkey "${key[Up]}" up-line-or-beginning-search
[[ -n ${key[Down]} ]] && bindkey "${key[Down]}" down-line-or-beginning-search

# AUTO COMPLETION
# ===============
autoload -Uz compinit
compinit -d $HOME/.cache/zsh.compdump
# move the cursor around the list of completions to select one
zstyle ':completion:*' menu select
# This way you tell zsh comp to take the first part of the path to be exact,
# and to avoid partial globs. Now path completions became nearly immediate.
zstyle ':completion:*' accept-exact '*(N)'
# autocomplete aliases
setopt COMPLETE_ALIASES

# DIRSTACK
# ========
DIRSTACKSIZE=0

# PROMPT
# ======
# See https://zsh.sourceforge.io/Doc/Release/Prompt-Expansion.html
PROMPT='
%d
%# '

# MISC
# ====
unsetopt beep

# disable XON/XOFF flow control (^s/^q)
stty -ixon

# set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"

source /opt/homebrew/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
